### ISSUE TITLE
ReactomeFINetwork with use.linkers = TRUE

### ISSUE THREAD

**Issue by kmezhoud** [funnell/reactomefi#15]
HI,
I get error with I set  use linkers = TRUE for all version. Any suggestion? Thanks Karim

 network <- ReactomeFINetwork("2013", GeneList, use.linkers=TRUE )
Opening and ending tag mismatch: HR line 34 and body
Opening and ending tag mismatch: HR line 1 and html
Premature end of data in tag body line 1
Premature end of data in tag html line 1
Error: 1: Opening and ending tag mismatch: HR line 34 and body
2: Opening and ending tag mismatch: HR line 1 and html
3: Premature end of data in tag body line 1
4: Premature end of data in tag html line 1

**Comment by funnell** [comment]
Hi Karim,

Sorry about this. Unfortunately it seems linkers=TRUE is broken. The package connects to the ReactomeFI plugin's web service, and it turns out that the linkers=TRUE functionality doesn't work on the web service. The Cytoscape plugin still works, because this functionality has been re-implemented in the plugin code itself!
I'll need to have a look at how the plugin code implements linker gene functionality.

**Comment by kmezhoud** [comment]
Hi Tyler,
I am not familiar with Java and eclipse to look also on it. 
I am interested to learn how reactomefi connects to the ReactomeFI web service. In which file can I find the connection code?
is the access to web service is public/free?
Thanks

**Comment by funnell** [comment]
This file https://github.com/funnell/reactomefi/blob/master/R/ReactomeFIService.R has functions that wraps some of the web service. Access to the web service is free and I suppose it's public, but not really documented, last I checked. I wrote the above file by looking at the plugin Java code, and by asking the plugin author for help, when needed.

**Comment by kmezhoud** [comment]
HI, 
use.linker =TRUE is fixed.
> getReactomeFI(2014, GeneList)
  first.protein second.protein
1         IFI16           TP53
2           PML           TP53
3         BRCA1           TP53
4         BRCA1          IFI16
5         BRCA1            NBN
> getReactomeFI(2014, GeneList, use.linkers = TRUE)
   first.protein second.protein
1            UBB          BRCA1
2           EGR1           DKK3
3           TP53          BRCA1
4            PML           TP53
5           TP53            UBB
6            NBN          BRCA1
7           TP53          IFI16
8           MYO6            UBB
9           EGR1           TP53
10          EGR1          BRCA1
11         IFI16          BRCA1
12          EGR1            UBB

**Comment by funnell** [comment]
This is encouraging! Did you just change the version year? Was this the same set of genes you first noticed the error with?

**Comment by kmezhoud** [comment]
All versions work. Not the same set of genes But I tried many genes.  Bad symbol may cause error message. 
Guanming Wu was fixed the error on the server.
